# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-11-04 23:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArmorAndShields',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minor_percent_chance_lower', models.IntegerField()),
                ('minor_percent_chance_upper', models.IntegerField()),
                ('medium_percent_chance_lower', models.IntegerField()),
                ('medium_percent_chance_upper', models.IntegerField()),
                ('major_percent_chance_lower', models.IntegerField()),
                ('major_percent_chance_upper', models.IntegerField()),
                ('item', models.CharField(max_length=130)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ArmorSpecialAbility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minor_percent_chance_lower', models.IntegerField()),
                ('minor_percent_chance_upper', models.IntegerField()),
                ('medium_percent_chance_lower', models.IntegerField()),
                ('medium_percent_chance_upper', models.IntegerField()),
                ('major_percent_chance_lower', models.IntegerField()),
                ('major_percent_chance_upper', models.IntegerField()),
                ('item_ability', models.CharField(max_length=120)),
                ('base_price_modifier', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ArmorType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percent_chance_lower', models.IntegerField()),
                ('percent_chance_upper', models.IntegerField()),
                ('type', models.CharField(max_length=120)),
                ('cost', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Art',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('art_percent_lower', models.IntegerField()),
                ('art_percent_upper', models.IntegerField()),
                ('art_value_dice_number', models.IntegerField()),
                ('art_value_dice_size', models.IntegerField()),
                ('art_name', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Gems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gems_percent_lower', models.IntegerField()),
                ('gems_percent_upper', models.IntegerField()),
                ('gem_value_dice_number', models.IntegerField()),
                ('gem_value_dice_size', models.IntegerField()),
                ('gem_name', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minor_percent_chance_lower', models.IntegerField()),
                ('minor_percent_chance_upper', models.IntegerField()),
                ('medium_percent_chance_lower', models.IntegerField()),
                ('medium_percent_chance_upper', models.IntegerField()),
                ('major_percent_chance_lower', models.IntegerField()),
                ('major_percent_chance_upper', models.IntegerField()),
                ('item_type', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='MundaneAlchemical',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percent_lower', models.IntegerField()),
                ('percent_upper', models.IntegerField()),
                ('number_of_dice', models.IntegerField()),
                ('size_of_dice', models.IntegerField()),
                ('cost_per', models.IntegerField()),
                ('item_name', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MundaneArmor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percent_lower', models.IntegerField()),
                ('percent_upper', models.IntegerField()),
                ('cost_per', models.IntegerField()),
                ('item_name', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MundaneItemBaseTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mundane_percent_lower', models.IntegerField()),
                ('mundane_percent_upper', models.IntegerField()),
                ('isAlchemical', models.BooleanField()),
                ('isArmor', models.BooleanField()),
                ('isWeapon', models.BooleanField()),
                ('isToolOrGear', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='MundaneToolOrGear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percent_lower', models.IntegerField()),
                ('percent_upper', models.IntegerField()),
                ('item_value', models.IntegerField()),
                ('item_name', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MundaneWeapons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percent_lower', models.IntegerField()),
                ('percent_upper', models.IntegerField()),
                ('item_name', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ShieldType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percent_chance_lower', models.IntegerField()),
                ('percent_chance_upper', models.IntegerField()),
                ('type', models.CharField(max_length=120)),
                ('cost', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TreasureCoinsBaseValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField()),
                ('coins_percent_lower', models.IntegerField()),
                ('coins_percent_upper', models.IntegerField()),
                ('coins_number_of_die', models.IntegerField()),
                ('coins_die_size', models.IntegerField()),
                ('coins_multiplier', models.IntegerField()),
                ('coins_type', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='TreasureGoodsBaseValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField()),
                ('goods_percent_lower', models.IntegerField()),
                ('goods_percent_upper', models.IntegerField()),
                ('goods_number_of_die', models.IntegerField()),
                ('goods_die_size', models.IntegerField()),
                ('goods_type', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='TreasureItemsBaseResults',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField()),
                ('items_percent_lower', models.IntegerField()),
                ('items_percent_upper', models.IntegerField()),
                ('items_number_of_die', models.IntegerField()),
                ('items_die_size', models.IntegerField()),
                ('items_type_mundane', models.BooleanField()),
                ('items_type_minor', models.BooleanField()),
                ('items_type_medium', models.BooleanField()),
                ('items_type_major', models.BooleanField()),
            ],
        ),
    ]
