# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-04 19:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArmorAndShields',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minor_percent_chance_lower', models.IntegerField()),
                ('minor_percent_chance_upper', models.IntegerField()),
                ('medium_percent_chance_lower', models.IntegerField()),
                ('medium_percent_chance_upper', models.IntegerField()),
                ('major_percent_chance_lower', models.IntegerField()),
                ('major_percent_chance_upper', models.IntegerField()),
                ('item', models.CharField(max_length=130)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ArmorSpecialAbility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minor_percent_chance_lower', models.IntegerField()),
                ('minor_percent_chance_upper', models.IntegerField()),
                ('medium_percent_chance_lower', models.IntegerField()),
                ('medium_percent_chance_upper', models.IntegerField()),
                ('major_percent_chance_lower', models.IntegerField()),
                ('major_percent_chance_upper', models.IntegerField()),
                ('item_ability', models.CharField(max_length=120)),
                ('base_price_modifier', models.IntegerField()),
                ('base_enhancement_bonus_modifier', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ArmorType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percent_chance_lower', models.IntegerField()),
                ('percent_chance_upper', models.IntegerField()),
                ('type', models.CharField(max_length=120)),
                ('cost', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Art',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percent_lower', models.IntegerField()),
                ('percent_upper', models.IntegerField()),
                ('value_dice_number', models.IntegerField()),
                ('value_dice_size', models.IntegerField()),
                ('value_multiplier', models.IntegerField()),
                ('art_name', models.CharField(max_length=800)),
            ],
        ),
        migrations.CreateModel(
            name='BaseMagicItemGenTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minor_percent_chance_lower', models.IntegerField()),
                ('minor_percent_chance_upper', models.IntegerField()),
                ('medium_percent_chance_lower', models.IntegerField()),
                ('medium_percent_chance_upper', models.IntegerField()),
                ('major_percent_chance_lower', models.IntegerField()),
                ('major_percent_chance_upper', models.IntegerField()),
                ('table_to_use', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Darkwood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percent_lower', models.IntegerField()),
                ('percent_upper', models.IntegerField()),
                ('type', models.CharField(max_length=80)),
                ('value', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Gems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percent_lower', models.IntegerField()),
                ('percent_upper', models.IntegerField()),
                ('value_dice_number', models.IntegerField()),
                ('value_dice_size', models.IntegerField()),
                ('value_multiplier', models.IntegerField()),
                ('gem_name', models.CharField(max_length=6000)),
            ],
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minor_percent_chance_lower', models.IntegerField()),
                ('minor_percent_chance_upper', models.IntegerField()),
                ('medium_percent_chance_lower', models.IntegerField()),
                ('medium_percent_chance_upper', models.IntegerField()),
                ('major_percent_chance_lower', models.IntegerField()),
                ('major_percent_chance_upper', models.IntegerField()),
                ('item_type', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='MagicWeapon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minor_percent_chance_lower', models.IntegerField()),
                ('minor_percent_chance_upper', models.IntegerField()),
                ('medium_percent_chance_lower', models.IntegerField()),
                ('medium_percent_chance_upper', models.IntegerField()),
                ('major_percent_chance_lower', models.IntegerField()),
                ('major_percent_chance_upper', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('cost', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Masterwork_Shield',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percent_lower', models.IntegerField()),
                ('percent_upper', models.IntegerField()),
                ('type', models.CharField(max_length=80)),
                ('value', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MundaneAlchemical',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percent_lower', models.IntegerField()),
                ('percent_upper', models.IntegerField()),
                ('number_of_dice', models.IntegerField()),
                ('size_of_dice', models.IntegerField()),
                ('cost_per', models.IntegerField()),
                ('item_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MundaneArmor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percent_lower', models.IntegerField()),
                ('percent_upper', models.IntegerField()),
                ('cost_per', models.IntegerField()),
                ('item_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MundaneItemBaseTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percent_lower', models.IntegerField()),
                ('percent_upper', models.IntegerField()),
                ('isAlchemical', models.BooleanField()),
                ('isArmor', models.BooleanField()),
                ('isWeapon', models.BooleanField()),
                ('isToolOrGear', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='MundaneToolOrGear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percent_lower', models.IntegerField()),
                ('percent_upper', models.IntegerField()),
                ('item_value', models.IntegerField()),
                ('item_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MundaneWeapons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percent_lower', models.IntegerField()),
                ('percent_upper', models.IntegerField()),
                ('item_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='RootMagicItemsTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minor_percent_chance_lower', models.IntegerField()),
                ('minor_percent_chance_upper', models.IntegerField()),
                ('medium_percent_chance_lower', models.IntegerField()),
                ('medium_percent_chance_upper', models.IntegerField()),
                ('major_percent_chance_lower', models.IntegerField()),
                ('major_percent_chance_upper', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ShieldSpecialAbility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minor_percent_chance_lower', models.IntegerField()),
                ('minor_percent_chance_upper', models.IntegerField()),
                ('medium_percent_chance_lower', models.IntegerField()),
                ('medium_percent_chance_upper', models.IntegerField()),
                ('major_percent_chance_lower', models.IntegerField()),
                ('major_percent_chance_upper', models.IntegerField()),
                ('item_ability', models.CharField(max_length=120)),
                ('base_price_modifier', models.IntegerField()),
                ('base_enhancement_bonus_modifier', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SpecificArmor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minor_percent_chance_lower', models.IntegerField()),
                ('minor_percent_chance_upper', models.IntegerField()),
                ('medium_percent_chance_lower', models.IntegerField()),
                ('medium_percent_chance_upper', models.IntegerField()),
                ('major_percent_chance_lower', models.IntegerField()),
                ('major_percent_chance_upper', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('cost', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SpecificShield',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minor_percent_chance_lower', models.IntegerField()),
                ('minor_percent_chance_upper', models.IntegerField()),
                ('medium_percent_chance_lower', models.IntegerField()),
                ('medium_percent_chance_upper', models.IntegerField()),
                ('major_percent_chance_lower', models.IntegerField()),
                ('major_percent_chance_upper', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('cost', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SpecificWeapon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minor_percent_chance_lower', models.IntegerField()),
                ('minor_percent_chance_upper', models.IntegerField()),
                ('medium_percent_chance_lower', models.IntegerField()),
                ('medium_percent_chance_upper', models.IntegerField()),
                ('major_percent_chance_lower', models.IntegerField()),
                ('major_percent_chance_upper', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('cost', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TreasureCoinsBaseValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField()),
                ('percent_lower', models.IntegerField()),
                ('percent_upper', models.IntegerField()),
                ('number_of_die', models.IntegerField()),
                ('die_size', models.IntegerField()),
                ('multiplier', models.IntegerField()),
                ('coins_type', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='TreasureGoodsBaseValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField()),
                ('percent_lower', models.IntegerField()),
                ('percent_upper', models.IntegerField()),
                ('number_of_die', models.IntegerField()),
                ('die_size', models.IntegerField()),
                ('goods_type', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='TreasureItemsBaseResults',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField()),
                ('percent_lower', models.IntegerField()),
                ('percent_upper', models.IntegerField()),
                ('number_of_die', models.IntegerField()),
                ('die_size', models.IntegerField()),
                ('items_type_mundane', models.BooleanField()),
                ('items_type_minor', models.BooleanField()),
                ('items_type_medium', models.BooleanField()),
                ('items_type_major', models.BooleanField()),
            ],
        ),
    ]
