# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-11-05 00:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Random_Gen', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='art',
            name='art_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='mundanealchemical',
            name='item_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='mundanearmor',
            name='item_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='mundanetoolorgear',
            name='item_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='mundaneweapons',
            name='item_name',
            field=models.CharField(max_length=50),
        ),
    ]
