# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-11-08 18:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Random_Gen', '0002_auto_20161104_1944'),
    ]

    operations = [
        migrations.RenameField(
            model_name='treasurecoinsbasevalue',
            old_name='coins_die_size',
            new_name='die_size',
        ),
        migrations.RenameField(
            model_name='treasurecoinsbasevalue',
            old_name='coins_multiplier',
            new_name='multiplier',
        ),
        migrations.RenameField(
            model_name='treasurecoinsbasevalue',
            old_name='coins_number_of_die',
            new_name='number_of_die',
        ),
        migrations.RenameField(
            model_name='treasurecoinsbasevalue',
            old_name='coins_percent_lower',
            new_name='percent_lower',
        ),
        migrations.RenameField(
            model_name='treasurecoinsbasevalue',
            old_name='coins_percent_upper',
            new_name='percent_upper',
        ),
        migrations.RenameField(
            model_name='treasuregoodsbasevalue',
            old_name='goods_die_size',
            new_name='die_size',
        ),
        migrations.RenameField(
            model_name='treasuregoodsbasevalue',
            old_name='goods_number_of_die',
            new_name='number_of_die',
        ),
        migrations.RenameField(
            model_name='treasuregoodsbasevalue',
            old_name='goods_percent_lower',
            new_name='percent_lower',
        ),
        migrations.RenameField(
            model_name='treasuregoodsbasevalue',
            old_name='goods_percent_upper',
            new_name='percent_upper',
        ),
        migrations.RenameField(
            model_name='treasureitemsbaseresults',
            old_name='items_die_size',
            new_name='die_size',
        ),
        migrations.RenameField(
            model_name='treasureitemsbaseresults',
            old_name='items_number_of_die',
            new_name='number_of_die',
        ),
        migrations.RenameField(
            model_name='treasureitemsbaseresults',
            old_name='items_percent_lower',
            new_name='percent_lower',
        ),
        migrations.RenameField(
            model_name='treasureitemsbaseresults',
            old_name='items_percent_upper',
            new_name='percent_upper',
        ),
    ]
